In [1]:
import numpy as np
import torch
import random

In [10]:
target = torch.tensor([[0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 0., 0., 1.]])
print(target.shape)
target

torch.Size([5, 5])


tensor([[0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 1., 0., 0., 1.]])

In [15]:
# np.nonzero(target.numpy())

In [16]:
# target = torch.zeros((5,5))
# print(target.shape)
# target

In [17]:
# target = torch.ones((5,5))
# print(target.shape)
# target

In [86]:
# target = np.zeros((5,5))
# target[0][0]=1
# print(target.shape)
# target

In [18]:
a = [[1,2],[4,5]]
for i,j in a:
    print(i)

1
4


In [195]:
n=2
target = torch.tensor(target)
triplet_indices = get_triplet_indices(target, n)
triplet_indices

/var/folders/5d/td2lpmcj3vq5wsprrdr42r9w0000gn/T/ipykernel_43943/516819316.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  target = torch.tensor(target)


(array([[4, 4],
        [3, 0]]),
 array([[3, 3],
        [2, 1]]),
 array([[1, 4],
        [0, 3]]))

In [22]:
output = torch.rand((3,2,5,5))
output

tensor([[[[0.3243, 0.8990, 0.0921, 0.2546, 0.9084],
          [0.5298, 0.9023, 0.2922, 0.7029, 0.0408],
          [0.3300, 0.9085, 0.5602, 0.9118, 0.9161],
          [0.3091, 0.5567, 0.9685, 0.8120, 0.1874],
          [0.3743, 0.9884, 0.8920, 0.4025, 0.9539]],

         [[0.3390, 0.1962, 0.3514, 0.1017, 0.7659],
          [0.8812, 0.9223, 0.7047, 0.0409, 0.2640],
          [0.6041, 0.9155, 0.6221, 0.8875, 0.5795],
          [0.4273, 0.3435, 0.9991, 0.3975, 0.6576],
          [0.3570, 0.8038, 0.5411, 0.5832, 0.6003]]],


        [[[0.3664, 0.0723, 0.8448, 0.4502, 0.1831],
          [0.7847, 0.5026, 0.4738, 0.9825, 0.0244],
          [0.8613, 0.9222, 0.6209, 0.7973, 0.3739],
          [0.0735, 0.1107, 0.6716, 0.2892, 0.0741],
          [0.3668, 0.6573, 0.3271, 0.8849, 0.0231]],

         [[0.5387, 0.6941, 0.0724, 0.7723, 0.5286],
          [0.5985, 0.2464, 0.9890, 0.9410, 0.0336],
          [0.5769, 0.9429, 0.7046, 0.8622, 0.8496],
          [0.2527, 0.1093, 0.8799, 0.8268, 0.3146],
    

In [253]:
tensor_triplets = get_output_triplets(output, triplet_indices)
tensor_triplets

(tensor([[0.3778, 0.2593],
         [0.6962, 0.0234]]),
 tensor([[0.0236, 0.6685],
         [0.6098, 0.3538]]),
 tensor([[0.8924, 0.0555],
         [0.8908, 0.9978]]))

In [329]:
def triplet_loss(tensor_triplets, margin=0.2):
    
    # unpack
    tensor_anchors,tensor_negatives, tensor_positives = tensor_triplets
    print(f'tensor_anchors:\n{tensor_anchors}\n')
    print(f'tensor_negatives:\n{tensor_negatives}\n')
    print(f'tensor_positives:\n{tensor_positives}\n')
    
    diff_anchor_positives = tensor_anchors - tensor_positives
    norm_anchor_positives = torch.linalg.norm(diff_anchor_positives)
    print(f'norm_anchor_positives:{norm_anchor_positives}')
    
    diff_anchor_negatives = tensor_anchors - tensor_negatives
    norm_anchor_negatives = torch.linalg.norm(diff_anchor_negatives)
    print(f'norm_anchor_negatives:{norm_anchor_negatives}')
    
    option1 = norm_anchor_positives - norm_anchor_negatives + margin
    option2 = 0.0
    
    loss = max(option1, option2)
    return float(loss)

In [347]:
loss = triplet_loss(tensor_triplets)
print(f'loss:{loss}')

tensor_anchors:
tensor([[0.3778, 0.2593],
        [0.6962, 0.0234]])

tensor_negatives:
tensor([[0.0236, 0.6685],
        [0.6098, 0.3538]])

tensor_positives:
tensor([[0.8924, 0.0555],
        [0.8908, 0.9978]])

norm_anchor_positives:1.137434959411621
norm_anchor_negatives:0.6399896740913391
loss:0.697445273399353


In [345]:
# def triplet_loss2(tensor_triplets, margin=0.2):
 
#     # unpack
#     tensor_anchors,tensor_negatives, tensor_positives = tensor_triplets
    
#     diff_anchor_positives = torch.cdist(tensor_anchors,tensor_positives,p=2.0)
#     print(f'diff_anchor_positives:\n{diff_anchor_positives}\n')
    
#     diff_anchor_negatives = torch.cdist(tensor_anchors,tensor_negatives,p=2.0)
#     print(f'diff_anchor_negatives:\n{diff_anchor_negatives}\n')
    
#     option1 = diff_anchor_positives - diff_anchor_negatives + margin
#     print(f'option1:\n{option1}\n')
    
#     option2 = 0.0
    
#     loss = max(option1, option2)
#     return float(loss)

In [348]:
# loss_alt = triplet_loss2(tensor_triplets)
# print(f'loss_alt:{loss_alt}')

In [341]:
targets = torch.stack([target,target])
print(targets.shape)
targets

torch.Size([2, 5, 5])


tensor([[[0., 0., 1., 1., 1.],
         [0., 0., 0., 1., 1.],
         [0., 0., 0., 0., 1.],
         [1., 0., 0., 0., 1.],
         [1., 1., 0., 0., 1.]],

        [[0., 0., 1., 1., 1.],
         [0., 0., 0., 1., 1.],
         [0., 0., 0., 0., 1.],
         [1., 0., 0., 0., 1.],
         [1., 1., 0., 0., 1.]]])

In [342]:
def loss(output, targets, n=1, margin=0.5):
    batch_loss = 0.0
    
    # for each output in the mini-batch, calculate triplet_loss
    for i in range(len(output)):
        target_i = targets[i]
        output_i = output[i]
#         print(output_i.shape)
        if len(output_i.shape) < 3:
            # output tensor must have at least 3 dimensions for function to work
            output_i = torch.unsqueeze(output_i, 0)
#         print(output_i.shape)
        
        
        
        # pixel indices
        triplet_indices_i = get_triplet_indices(target_i, n)
        print(triplet_indices_i)
        
        # output pixels
        tensor_triplets_i = get_output_triplets(output_i, triplet_indices_i)
#         print(tensor_triplets_i)
        
        # calculate loss
        loss_i = triplet_loss(tensor_triplets_i, margin)
        batch_loss += loss_i
        
    return batch_loss

In [302]:
loss(output, targets)

0.7193681001663208

In [26]:
anchor = torch.tensor([[0.0,0,0]])
positive = torch.tensor([[0.0,0,2]])
print(anchor)
print(positive)

torch.cdist(anchor, positive, p=2.0)

tensor([[0., 0., 0.]])
tensor([[0., 0., 2.]])


tensor([[2.]])